# -*- coding: utf-8 -*-
"""ARCI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M95MEbtDxwn9BaSvHkqajfX7QCtDCJj_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive
drive.mount('drive')

"""Matrices SECRE"""

datos="/content/drive/MyDrive/UAM-UNAM/Censos/SAIC_Exporta_2022528_203255835.csv"

csv=pd.read_csv(datos, encoding="latin-1")
csv=csv.iloc[:,:28]
csv=csv.drop(csv.index[[0,1,2,3,1078216,1078217,1078218]])
csv

csv.columns=["year", "entidad", "municipio", "ae", "ue", "pot", "tr", "pbt", "vacb",
             "it", "fbcf", "ataf", "ctaf", "vtaf", "afpup", "htpot", "ppvst",
             "htppvst", "pacdt", "htpacdt",	"tsppvs", "tspacd", "ccle",
             "gcee", "cspct", "ca", "atmep", "atecp"]
csv.head()

csv["localidad"]=csv["entidad"]+" "+csv["municipio"]
csv.drop(['entidad', 'municipio'], axis=1)
csv=csv[["year", "localidad", "ae", "ue", "pot", "tr", "pbt", "vacb",
             "it", "fbcf", "ataf", "ctaf", "vtaf", "afpup", "htpot", "ppvst",
             "htppvst", "pacdt", "htpacdt",	"tsppvs", "tspacd", "ccle",
             "gcee", "cspct", "ca", "atmep", "atecp"]]
csv.head()

csv.shape

csv.year.unique()

csv["year"]=csv.year.astype(int)

matrices=[]
for columna in ["ue", "pot", "tr", "pbt", "vacb",
             "it", "fbcf", "ataf", "ctaf", "vtaf", "afpup", "htpot", "ppvst",
             "htppvst", "pacdt", "htpacdt",	"tsppvs", "tspacd", "ccle",
             "gcee", "cspct", "ca", "atmep", "atecp"]:
  for year in [2003,2008,2013,2018]:
    csv_temp=csv[csv["year"]==year]
    pivote=csv_temp.pivot("ae","localidad",columna)
    pivote.loc['tc']=pivote.sum(axis=0)
    pivote.loc[:,'tf']=pivote.sum(axis=1)
    pc=pivote.pop('tf')
    pivote.insert(0, 'tf', pc)
    titulo=columna+"_"+str(year)+".csv"
    matrices.append(titulo)
    pivote.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+titulo)

print(matrices)

"""Matrices generadas"""

matrices=['ue_2003.csv', 'ue_2008.csv', 'ue_2013.csv', 'ue_2018.csv', 'pot_2003.csv', 'pot_2008.csv', 'pot_2013.csv', 'pot_2018.csv', 'tr_2003.csv', 'tr_2008.csv', 'tr_2013.csv', 'tr_2018.csv', 'pbt_2003.csv', 'pbt_2008.csv', 'pbt_2013.csv', 'pbt_2018.csv', 'vacb_2003.csv', 'vacb_2008.csv', 'vacb_2013.csv', 'vacb_2018.csv', 'it_2003.csv', 'it_2008.csv', 'it_2013.csv', 'it_2018.csv', 'fbcf_2003.csv', 'fbcf_2008.csv', 'fbcf_2013.csv', 'fbcf_2018.csv', 'ataf_2003.csv', 'ataf_2008.csv', 'ataf_2013.csv', 'ataf_2018.csv', 'ctaf_2003.csv', 'ctaf_2008.csv', 'ctaf_2013.csv', 'ctaf_2018.csv', 'vtaf_2003.csv', 'vtaf_2008.csv', 'vtaf_2013.csv', 'vtaf_2018.csv', 'afpup_2003.csv', 'afpup_2008.csv', 'afpup_2013.csv', 'afpup_2018.csv', 'htpot_2003.csv', 'htpot_2008.csv', 'htpot_2013.csv', 'htpot_2018.csv', 'ppvst_2003.csv', 'ppvst_2008.csv', 'ppvst_2013.csv', 'ppvst_2018.csv', 'htppvst_2003.csv', 'htppvst_2008.csv', 'htppvst_2013.csv', 'htppvst_2018.csv', 'pacdt_2003.csv', 'pacdt_2008.csv', 'pacdt_2013.csv', 'pacdt_2018.csv', 'htpacdt_2003.csv', 'htpacdt_2008.csv', 'htpacdt_2013.csv', 'htpacdt_2018.csv', 'tsppvs_2003.csv', 'tsppvs_2008.csv', 'tsppvs_2013.csv', 'tsppvs_2018.csv', 'tspacd_2003.csv', 'tspacd_2008.csv', 'tspacd_2013.csv', 'tspacd_2018.csv', 'ccle_2003.csv', 'ccle_2008.csv', 'ccle_2013.csv', 'ccle_2018.csv', 'gcee_2003.csv', 'gcee_2008.csv', 'gcee_2013.csv', 'gcee_2018.csv', 'cspct_2003.csv', 'cspct_2008.csv', 'cspct_2013.csv', 'cspct_2018.csv', 'ca_2003.csv', 'ca_2008.csv', 'ca_2013.csv', 'ca_2018.csv', 'atmep_2003.csv', 'atmep_2008.csv', 'atmep_2013.csv', 'atmep_2018.csv', 'atecp_2003.csv', 'atecp_2008.csv', 'atecp_2013.csv', 'atecp_2018.csv']

tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices[0], index_col="ae")
tabla.fillna(0, inplace=True)
tabla[278:281]

with open("/content/drive/MyDrive/UAM-UNAM/Censos/Matrices_INEGI.txt",'w+',encoding = 'utf-8') as f:
    for linea in matrices:
      f.write(linea+"\n")

ruta="/content/drive/MyDrive/UAM-UNAM/Censos/"
f= open(ruta+"Matrices_INEGI.txt","r")
lista_archivos=f.read().split()
clave=''
matrices=[nombre_archivo for nombre_archivo in lista_archivos if clave in nombre_archivo]
matrices

"""# Índices de Localización y Especialización

Pij
"""

# Convirtiendo todos los valores de la matriz a arreglo
x=tabla.to_numpy()
# Seleccionando la fila de totales como denominador
y=tabla.to_numpy()[-1,:]
# Dividiendo y creando la nueva matriz
division=np.divide(x,y)
P_ij=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
P_ij

"""Pji"""

# Convirtiendo todos los valores de la matriz a arreglo
x=tabla.to_numpy()
# Seleccionando la fila de totales como denominador
y=tabla.to_numpy()[:,0]
# Dividiendo y creando la nueva matriz
division=np.divide(x.T,y)
P_ji=pd.DataFrame(data=division.T, index=tabla.index, columns=tabla.columns)
P_ji

"""Qij"""

# Convirtiendo todos los valores de la matriz a arreglo
x=tabla.to_numpy()[-1,:]
# Seleccionando la fila de totales como denominador
y=tabla.to_numpy()[-1,0]
# Dividiendo y creando la nueva matriz
division=np.divide(x,y)
denominador=pd.DataFrame(data=division).T
denominador.columns=tabla.columns
denominador.index=["tc"]
denominador
# Realizando la división de matrices
division=np.divide(P_ji.to_numpy(),denominador.to_numpy())
Q_ij=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
Q_ij

"""Qr"""

# Convirtiendo todos los valores de la matriz a arreglo
x=tabla.to_numpy()[:,0]
# Seleccionando la fila de totales como denominador
y=tabla.to_numpy()[-1,0]
# Dividiendo y creando la nueva matriz
division=np.divide(x,y)
denominador2=pd.DataFrame(data=division)
denominador2.columns=["tc"]
denominador2.index=tabla.index
denominador2
ceros=np.zeros(P_ij.shape)
for j in range(P_ij.shape[1]):
  for i in range(P_ij.shape[0]):
    ceros[i,j]=(1/2)*abs((P_ij.iloc[i,j]-denominador2.iloc[i]))
Q_R=pd.DataFrame(data=ceros, columns=tabla.columns, index=tabla.index)
Q_R

"""Generación de resultados"""

matrices_coeficientes=[]
for matriz in matrices:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices[0], index_col="ae")
  tabla.fillna(0, inplace=True)
  ##############################################################################
  ###    P_ij   ####
  titulo="P_ij_"+matriz+".csv"
  x=tabla.to_numpy()
  y=tabla.to_numpy()[-1,:]
  division=np.divide(x,y)
  P_ij=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  P_ij.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/P_ij/"+titulo)
  matrices_coeficientes.append(titulo)
##############################################################################
  ###    P_ji   ####
  titulo="P_ji_"+matriz+".csv"
  x=tabla.to_numpy()
  y=tabla.to_numpy()[:,0]
  # Dividiendo y creando la nueva matriz
  division=np.divide(x.T,y)
  P_ji=pd.DataFrame(data=division.T, index=tabla.index, columns=tabla.columns)
  P_ji.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/P_ji/"+titulo)
  matrices_coeficientes.append(titulo)
  ##############################################################################
  ###    Q_ij   ####
  titulo="Q_ij_"+matriz+".csv"
  x=tabla.to_numpy()[-1,:]
  y=tabla.to_numpy()[-1,0]
  division=np.divide(x,y)
  denominador=pd.DataFrame(data=division).T
  denominador.columns=tabla.columns
  denominador.index=["tc"]
  division=np.divide(P_ji.to_numpy(),denominador.to_numpy())
  Q_ij=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  Q_ij.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Q_ij/"+titulo)
  matrices_coeficientes.append(titulo)

##############################################################################
  ###    Q_R   ####
  titulo="Q_R_"+matriz
  # Convirtiendo todos los valores de la matriz a arreglo
  x=tabla.to_numpy()[:,0]
  # Seleccionando la fila de totales como denominador
  y=tabla.to_numpy()[-1,0]
  # Dividiendo y creando la nueva matriz
  division=np.divide(x,y)
  denominador2=pd.DataFrame(data=division)
  denominador2.columns=["tc"]
  denominador2.index=tabla.index
  ceros=np.zeros(P_ij.shape)
  for j in range(P_ij.shape[1]):
    for i in range(P_ij.shape[0]):
      ceros[i,j]=abs((P_ij.iloc[i,j]-denominador2.iloc[i])/2)
  Q_R=pd.DataFrame(data=ceros, columns=tabla.columns, index=tabla.index)
  Q_R.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Q_R/"+titulo)
  matrices_coeficientes.append(titulo)

"""# Productividad y Eficiencia

2003
"""

matrices03=['ue_2003.csv','it_2003.csv','fbcf_2003.csv','ataf_2003.csv','ctaf_2003.csv',
            'vtaf_2003.csv','afpup_2003.csv','ccle_2003.csv','gcee_2003.csv','cspct_2003.csv',
            'ca_2003.csv','atmep_2003.csv','atecp_2003.csv', 'pot_2003.csv',
            'ppvst_2003.csv','pacdt_2003.csv','htpot_2003.csv','htppvst_2003.csv','htpacdt_2003.csv',
            'tr_2003.csv','tsppvs_2003.csv','tspacd_2003.csv', 'pbt_2003.csv','vacb_2003.csv']

matrices03[16]

matrices_coeficientes=[]
for matriz in matrices03:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices03[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices03[13], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###    Productividad con respecto a la población ocupada ####
  titulo="Prodpot"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Productividad/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices03:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices03[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices03[14], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###    Productividad con respecto a la población de producción, ventas y servicios ####
  titulo="Prodppvst"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Productividad/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices03:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices03[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices03[15], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###    Productividad con respecto a la población administrativa, contable y dirección  ####
  titulo="Prodpacdt"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Productividad/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices03:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices03[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices03[16], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###    Productividad con respecto a las horas trabajadas pot  ####
  titulo="Prodhtpot"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Productividad/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices03:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices03[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices03[17], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###    Productividad con respecto a las horas trabajadas ppvst  ####
  titulo="Prodhtppvst"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Productividad/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices03:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices03[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices03[18], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###    Productividad con respecto a las horas trabajadas pacdt  ####
  titulo="Prodhtpacdt"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Productividad/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices03:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices03[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices03[19], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###  Peso de las remuneraciones totales  ####
  titulo="Rt"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Remuneraciones/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices03:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices03[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices03[20], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###  Peso de las remuneraciones al ppvst  ####
  titulo="Rppvst"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Remuneraciones/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices03:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices03[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices03[21], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###  Peso de las remuneraciones al pacdt  ####
  titulo="Rpacdt"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Remuneraciones/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices03:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices03[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices03[22], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###  Eficiencia en términos del pbt  ####
  titulo="Efi"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Eficiencia/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices03:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices03[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices03[23], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###  Capacidades en términos del vacb  ####
  titulo="Cap"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Capacidades/"+titulo)
  matrices_coeficientes.append(titulo)

"""2008"""

matrices08=['ue_2008.csv','it_2008.csv','fbcf_2008.csv','ataf_2008.csv','ctaf_2008.csv','vtaf_2008.csv',
            'afpup_2008.csv','ccle_2008.csv','gcee_2008.csv','cspct_2008.csv','ca_2008.csv',
            'atmep_2008.csv','atecp_2008.csv','pot_2008.csv','ppvst_2008.csv','pacdt_2008.csv',
            'htpot_2008.csv','htppvst_2008.csv','htpacdt_2008.csv','tr_2008.csv','tsppvs_2008.csv',
            'tspacd_2008.csv','pbt_2008.csv','vacb_2008.csv']

matrices_coeficientes=[]
for matriz in matrices08:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices08[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices08[13], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###    Productividad con respecto a la población ocupada ####
  titulo="Prodpot"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Productividad/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices08:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices08[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices08[14], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###    Productividad con respecto a la población de producción, ventas y servicios ####
  titulo="Prodppvst"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Productividad/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices08:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices08[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices08[15], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###    Productividad con respecto a la población administrativa, contable y dirección  ####
  titulo="Prodpacdt"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Productividad/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices08:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices08[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices08[16], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###    Productividad con respecto a las horas trabajadas pot  ####
  titulo="Prodhtpot"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Productividad/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices08:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices08[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices08[17], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###    Productividad con respecto a las horas trabajadas ppvst  ####
  titulo="Prodhtppvst"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Productividad/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices08:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices08[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices08[18], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###    Productividad con respecto a las horas trabajadas pacdt  ####
  titulo="Prodhtpacdt"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Productividad/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices08:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices08[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices08[19], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###  Peso de las remuneraciones totales  ####
  titulo="Rt"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Remuneraciones/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices08:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices08[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices08[20], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###  Peso de las remuneraciones al ppvst  ####
  titulo="Rppvst"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Remuneraciones/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices08:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices08[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices08[21], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###  Peso de las remuneraciones al pacdt  ####
  titulo="Rpacdt"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Remuneraciones/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices08:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices08[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices08[22], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###  Eficiencia en términos del pbt  ####
  titulo="Efi"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Eficiencia/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices08:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices08[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices08[23], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###  Capacidades en términos del vacb  ####
  titulo="Cap"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Capacidades/"+titulo)
  matrices_coeficientes.append(titulo)

2013

matrices13=['ue_2013.csv','it_2013.csv','fbcf_2013.csv','ataf_2013.csv','ctaf_2013.csv','vtaf_2013.csv',
            'afpup_2013.csv','ccle_2013.csv','gcee_2013.csv','cspct_2013.csv','ca_2013.csv',
            'atmep_2013.csv','atecp_2013.csv','pot_2013.csv','ppvst_2013.csv','pacdt_2013.csv',
            'htpot_2013.csv','htppvst_2013.csv','htpacdt_2013.csv','tr_2013.csv','tsppvs_2013.csv',
            'tspacd_2013.csv', 'pbt_2013.csv','vacb_2013.csv']

matrices_coeficientes=[]
for matriz in matrices13:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices13[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices13[13], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###    Productividad con respecto a la población ocupada ####
  titulo="Prodpot"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Productividad/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices13:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices13[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices13[14], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###    Productividad con respecto a la población de producción, ventas y servicios ####
  titulo="Prodppvst"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Productividad/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices13:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices13[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices13[15], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###    Productividad con respecto a la población administrativa, contable y dirección  ####
  titulo="Prodpacdt"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Productividad/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices13:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices13[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices13[16], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###    Productividad con respecto a las horas trabajadas pot  ####
  titulo="Prodhtpot"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Productividad/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices13:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices13[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices13[17], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###    Productividad con respecto a las horas trabajadas ppvst  ####
  titulo="Prodhtppvst"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Productividad/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices13:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices13[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices13[18], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###    Productividad con respecto a las horas trabajadas pacdt  ####
  titulo="Prodhtpacdt"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Productividad/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices13:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices13[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices13[19], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###  Peso de las remuneraciones totales  ####
  titulo="Rt"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Remuneraciones/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices13:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices13[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices13[20], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###  Peso de las remuneraciones al ppvst  ####
  titulo="Rppvst"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Remuneraciones/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices13:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices13[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices13[21], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###  Peso de las remuneraciones al pacdt  ####
  titulo="Rpacdt"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Remuneraciones/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices13:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices13[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices13[22], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###  Eficiencia en términos del pbt  ####
  titulo="Efi"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Eficiencia/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices13:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices13[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices13[23], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###  Capacidades en términos del vacb  ####
  titulo="Cap"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Capacidades/"+titulo)
  matrices_coeficientes.append(titulo)

"""2018"""

matrices18=['ue_2018.csv','it_2018.csv','fbcf_2018.csv','ataf_2018.csv','ctaf_2018.csv','vtaf_2018.csv',
            'afpup_2018.csv','ccle_2018.csv','gcee_2018.csv','cspct_2018.csv','ca_2018.csv',
            'atmep_2018.csv','atecp_2018.csv','pot_2018.csv','ppvst_2018.csv','pacdt_2018.csv',
            'htpot_2018.csv','htppvst_2018.csv','htpacdt_2018.csv','tr_2018.csv','tsppvs_2018.csv',
            'tspacd_2018.csv', 'pbt_2018.csv','vacb_2018.csv']

matrices_coeficientes=[]
for matriz in matrices18:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices18[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices18[13], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###    Productividad con respecto a la población ocupada ####
  titulo="Prodpot"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Productividad/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices18:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices18[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices18[14], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###    Productividad con respecto a la población de producción, ventas y servicios ####
  titulo="Prodppvst"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Productividad/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices18:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices18[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices18[15], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###    Productividad con respecto a la población administrativa, contable y dirección  ####
  titulo="Prodpacdt"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Productividad/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices18:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices18[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices18[16], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###    Productividad con respecto a las horas trabajadas pot  ####
  titulo="Prodhtpot"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Productividad/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices18:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices18[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices18[17], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###    Productividad con respecto a las horas trabajadas ppvst  ####
  titulo="Prodhtppvst"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Productividad/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices18:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices18[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices18[18], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###    Productividad con respecto a las horas trabajadas pacdt  ####
  titulo="Prodhtpacdt"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Productividad/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices18:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices18[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices18[19], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###  Peso de las remuneraciones totales  ####
  titulo="Rt"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Remuneraciones/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices18:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices18[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices18[20], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###  Peso de las remuneraciones al ppvst  ####
  titulo="Rppvst"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Remuneraciones/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices18:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices18[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices18[21], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###  Peso de las remuneraciones al pacdt  ####
  titulo="Rpacdt"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Remuneraciones/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices18:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices18[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices18[22], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###  Eficiencia en términos del pbt  ####
  titulo="Efi"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Eficiencia/"+titulo)
  matrices_coeficientes.append(titulo)

matrices_coeficientes=[]
for matriz in matrices18:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices18[0], index_col="ae")
  tabla1=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/Censos/SECRE/"+matrices18[23], index_col="ae")
  tabla.fillna(0, inplace=True)
  tabla1.fillna(0, inplace=True)
  ##############################################################################
  ###  Capacidades en términos del vacb  ####
  titulo="Cap"+matriz
  x=tabla.to_numpy()
  y=tabla1.to_numpy()
  division=np.divide(x,y)
  prodpob=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  prodpob.to_csv("/content/drive/MyDrive/UAM-UNAM/Censos/Capacidades/"+titulo)
  matrices_coeficientes.append(titulo)