# -*- coding: utf-8 -*-
"""basededatos03_18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jwx8d3l9ZQT0bYZt2Ck_nxwXit4rDPSx
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive
drive.mount('drive')

"""Matrices SECRE"""

datos="/content/basind.csv"

datos

csv=pd.read_csv(datos)

csv

matrices=[]
for columna in ["ue", "pot", "tre", "pbt", "vacb",
              "int", "fbcf", "ataf", "dtaf", "tog", "toi","ctaf", "vtaf", "afup", "htpot",
              "htppvs","pacd","ppvs", "htpacd", "tsppvs", "tspacd", "cpao","ccle", "cee",
              "rabi", "cspct", "gsc", "rrmc","cag", "gcee",
              "atmep", "atbi", "atet","atecp", "atmo", "roa", "rat", "iaf", "roic", "dca",
               "pbt_ataf",	"pbt_afup",	"pbt_atmep",	"pbt_atbi",	"pbt_atet",	"pbt_atecp",
                "pbt_atmo",	"pbt_htpot",	"pbt_htppvs",	"pbt_htpacd",	"pbt_cpao",	"pbt_ccle",
                "pbt_cee",	"pbt_rabi",	"pbt_cspct",	"pbt_gsc",	"pbt_rrmc",
                "pbt_cag",	"pbt_gcee",	"tre_htpot",	"tre_htppvs",	"tre_htpacd",	"tsppvs_tre",
                "tspacd_tre",	"vacb_htpot",	"vacb_htppvs",	"vacb_htpacd",	"vacb_ataf",
                "vacb_afup",	"vacb_atmep",	"vacb_atbi",	"vacb_atet",	"vacb_atecp",	"vacb_atmo" ]:
  for AC in [2018, 2013, 2008, 2003]:
    csv_temp=csv[csv["AC"]== AC]
    pivote=csv_temp.pivot("AE","EF",columna)
    pivote.loc['tc']=pivote.sum(axis=0)
    pivote.loc[:,'tf']=pivote.sum(axis=1)
    pc=pivote.pop('tf')
    pivote.insert(0, 'tf', pc)
    titulo=columna+"_"+str(AC)+".csv"
    matrices.append(titulo)
    pivote.to_csv("/content/drive/MyDrive/UAM-UNAM/secregen/"+titulo)

print(matrices)

"""Matrices generadas"""

matrices=['ue_2003.csv', 'ue_2008.csv', 'ue_2013.csv', 'ue_2018.csv', 'pot_2003.csv', 'pot_2008.csv', 'pot_2013.csv', 'pot_2018.csv', 'tr_2003.csv', 'tr_2008.csv', 'tr_2013.csv', 'tr_2018.csv', 'pbt_2003.csv', 'pbt_2008.csv', 'pbt_2013.csv', 'pbt_2018.csv', 'vacb_2003.csv', 'vacb_2008.csv', 'vacb_2013.csv', 'vacb_2018.csv', 'it_2003.csv', 'it_2008.csv', 'it_2013.csv', 'it_2018.csv', 'fbcf_2003.csv', 'fbcf_2008.csv', 'fbcf_2013.csv', 'fbcf_2018.csv', 'ataf_2003.csv', 'ataf_2008.csv', 'ataf_2013.csv', 'ataf_2018.csv', 'ctaf_2003.csv', 'ctaf_2008.csv', 'ctaf_2013.csv', 'ctaf_2018.csv', 'vtaf_2003.csv', 'vtaf_2008.csv', 'vtaf_2013.csv', 'vtaf_2018.csv', 'afpup_2003.csv', 'afpup_2008.csv', 'afpup_2013.csv', 'afpup_2018.csv', 'htpot_2003.csv', 'htpot_2008.csv', 'htpot_2013.csv', 'htpot_2018.csv', 'ppvst_2003.csv', 'ppvst_2008.csv', 'ppvst_2013.csv', 'ppvst_2018.csv', 'htppvst_2003.csv', 'htppvst_2008.csv', 'htppvst_2013.csv', 'htppvst_2018.csv', 'pacdt_2003.csv', 'pacdt_2008.csv', 'pacdt_2013.csv', 'pacdt_2018.csv', 'htpacdt_2003.csv', 'htpacdt_2008.csv', 'htpacdt_2013.csv', 'htpacdt_2018.csv', 'tsppvs_2003.csv', 'tsppvs_2008.csv', 'tsppvs_2013.csv', 'tsppvs_2018.csv', 'tspacd_2003.csv', 'tspacd_2008.csv', 'tspacd_2013.csv', 'tspacd_2018.csv', 'ccle_2003.csv', 'ccle_2008.csv', 'ccle_2013.csv', 'ccle_2018.csv', 'gcee_2003.csv', 'gcee_2008.csv', 'gcee_2013.csv', 'gcee_2018.csv', 'cspct_2003.csv', 'cspct_2008.csv', 'cspct_2013.csv', 'cspct_2018.csv', 'ca_2003.csv', 'ca_2008.csv', 'ca_2013.csv', 'ca_2018.csv', 'atmep_2003.csv', 'atmep_2008.csv', 'atmep_2013.csv', 'atmep_2018.csv', 'atecp_2003.csv', 'atecp_2008.csv', 'atecp_2013.csv', 'atecp_2018.csv']

tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/secregen/"+matrices[0], index_col="AE")
tabla.fillna(0, inplace=True)
tabla

with open("/content/drive/MyDrive/UAM-UNAM/secregen/Matrices_INEGI.txt",'w+',encoding = 'utf-8') as f:
    for linea in matrices:
      f.write(linea+"\n")

ruta="/content/drive/MyDrive/UAM-UNAM/secregen/"
f= open(ruta+"Matrices_INEGI.txt","r")
lista_archivos=f.read().split()
clave=''
matrices=[nombre_archivo for nombre_archivo in lista_archivos if clave in nombre_archivo]
matrices

"""# Índices de Localización y Especialización

Pij
"""

# Convirtiendo todos los valores de la matriz a arreglo
x=tabla.to_numpy()
# Seleccionando la fila de totales como denominador
y=tabla.to_numpy()[-1,:]
# Dividiendo y creando la nueva matriz
division=np.divide(x,y)
P_ij=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
P_ij

"""Pji"""

# Convirtiendo todos los valores de la matriz a arreglo
x=tabla.to_numpy()
# Seleccionando la fila de totales como denominador
y=tabla.to_numpy()[:,0]
# Dividiendo y creando la nueva matriz
division=np.divide(x.T,y)
P_ji=pd.DataFrame(data=division.T, index=tabla.index, columns=tabla.columns)
P_ji

"""Qij"""

# Convirtiendo todos los valores de la matriz a arreglo
x=tabla.to_numpy()[-1,:]
# Seleccionando la fila de totales como denominador
y=tabla.to_numpy()[-1,0]
# Dividiendo y creando la nueva matriz
division=np.divide(x,y)
denominador=pd.DataFrame(data=division).T
denominador.columns=tabla.columns
denominador.index=["tc"]
denominador
# Realizando la división de matrices
division=np.divide(P_ji.to_numpy(),denominador.to_numpy())
Q_ij=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
Q_ij

"""Qr"""

# Convirtiendo todos los valores de la matriz a arreglo
x=tabla.to_numpy()[:,0]
# Seleccionando la fila de totales como denominador
y=tabla.to_numpy()[-1,0]
# Dividiendo y creando la nueva matriz
division=np.divide(x,y)
denominador2=pd.DataFrame(data=division)
denominador2.columns=["tc"]
denominador2.index=tabla.index
denominador2
ceros=np.zeros(P_ij.shape)
for j in range(P_ij.shape[1]):
  for i in range(P_ij.shape[0]):
    ceros[i,j]=(1/2)*abs((P_ij.iloc[i,j]-denominador2.iloc[i]))
Q_R=pd.DataFrame(data=ceros, columns=tabla.columns, index=tabla.index)
Q_R

"""Generación de resultados"""

matrices_coeficientes=[]
for matriz in matrices:
  tabla=pd.read_csv("/content/drive/MyDrive/UAM-UNAM/secregen/"+matrices[0], index_col="AE")
  tabla.fillna(0, inplace=True)
  ##############################################################################
  ###    P_ij   ####
  titulo="P_ij_"+matriz+".csv"
  x=tabla.to_numpy()
  y=tabla.to_numpy()[-1,:]
  division=np.divide(x,y)
  P_ij=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  P_ij.to_csv("/content/drive/MyDrive/UAM-UNAM/secregen/P_ij/"+titulo)
  matrices_coeficientes.append(titulo)
##############################################################################
  ###    P_ji   ####
  titulo="P_ji_"+matriz+".csv"
  x=tabla.to_numpy()
  y=tabla.to_numpy()[:,0]
  # Dividiendo y creando la nueva matriz
  division=np.divide(x.T,y)
  P_ji=pd.DataFrame(data=division.T, index=tabla.index, columns=tabla.columns)
  P_ji.to_csv("/content/drive/MyDrive/UAM-UNAM/secregen/P_ji/"+titulo)
  matrices_coeficientes.append(titulo)
  ##############################################################################
  ###    Q_ij   ####
  titulo="Q_ij_"+matriz+".csv"
  x=tabla.to_numpy()[-1,:]
  y=tabla.to_numpy()[-1,0]
  division=np.divide(x,y)
  denominador=pd.DataFrame(data=division).T
  denominador.columns=tabla.columns
  denominador.index=["tc"]
  division=np.divide(P_ji.to_numpy(),denominador.to_numpy())
  Q_ij=pd.DataFrame(data=division, index=tabla.index, columns=tabla.columns)
  Q_ij.to_csv("/content/drive/MyDrive/UAM-UNAM/secregen/Q_ij/"+titulo)
  matrices_coeficientes.append(titulo)

##############################################################################
  ###    Q_r   ####
  titulo="Q_r_"+matriz
  # Convirtiendo todos los valores de la matriz a arreglo
  x=tabla.to_numpy()[:,0]
  # Seleccionando la fila de totales como denominador
  y=tabla.to_numpy()[-1,0]
  # Dividiendo y creando la nueva matriz
  division=np.divide(x,y)
  denominador2=pd.DataFrame(data=division)
  denominador2.columns=["tc"]
  denominador2.index=tabla.index
  ceros=np.zeros(P_ij.shape)
  for j in range(P_ij.shape[1]):
    for i in range(P_ij.shape[0]):
      ceros[i,j]=abs((P_ij.iloc[i,j]-denominador2.iloc[i])/2)
  Q_R=pd.DataFrame(data=ceros, columns=tabla.columns, index=tabla.index)
  Q_R.to_csv("/content/drive/MyDrive/UAM-UNAM/secregen/Q_r/"+titulo)
  matrices_coeficientes.append(titulo)