# -*- coding: utf-8 -*-
"""censospoblacionales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lZ9Aqc3QwEAqzB_ipPbS66YynpWjv02E
"""

import pandas as pd
!pip install INEGIpy
!pip list

!pip list INEGIpy

from INEGIpy import INEGI