# -*- coding: utf-8 -*-
"""ENVI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NB6pB9CsPTC4yUuT7UbqWxB7AEzb1QQ9
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive
drive.mount('drive')

data = pd.read_csv('/content/drive/MyDrive/ENVI/Bases de datos/TVIVIENDA.csv', index_col = 0)
data = data.loc[:,['ENT','P5_1','FACTOR']]
data

datafil = data[(data.P5_1==1)]
datafil

datafil['renta']=datafil.P5_1*datafil.FACTOR
datafil

estados = datafil.groupby('ENT').renta.count()
estados

!pip install geopandas

import geopandas as gdp

mapa='/content/drive/MyDrive/ENVI/Bases de datos/mexicoHigh.json'

ENT=range(1,33)
mapamex=gdp.read_file(mapa)
mapamex=mapamex.sort_values('name')
mapamex['ENT']=ENT
mapamex=mapamex.set_index('ENT')
mapamex['renta'] = estados
mapamex['hogares']=mapamex.renta.apply(lambda x: (35300000*x)/55147)
mapamex['porcentaje']=mapamex.hogares.apply(lambda x: (100*x)/35300000)
mapamex

fig = plt.figure(figsize=(7, 7))
ax = fig.add_subplot(111)
title = 'Porcentaje de Hogares que habitan en alquiler'
plt.title(title + '\n', fontsize=19)
mapamex.plot(column='porcentaje', cmap='plasma', ax=ax, zorder=5)
ax.set_xlabel('Longitud', fontsize = 12)
ax.set_ylabel('Latitud', fontsize = 12)
min_p = min(mapamex['porcentaje'])
max_p = max(mapamex['porcentaje'])
bar = plt.cm.ScalarMappable(cmap='plasma',
 norm=plt.Normalize(vmin = min_p , vmax=max_p))
bar._A = []
cax = plt.axes([0.95, 0.1, 0.01, 0.7])
cbar = fig.colorbar(bar, cax=cax)
cbar.set_label('Hogares', fontsize = 12)
plt.savefig('renta.jpg', dpi = 200)